stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: covidsc-web:${CICD_GIT_BRANCH}
      registry: 127.0.0.1:34422
- name: Deploy Master
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: |-
        cd deployment
        sed -i "s/BUILD_NUM/build${CICD_EXECUTION_SEQUENCE}/g" development.yaml
  - applyYamlConfig:
      path: ./deployment/development.yaml
  when:
    branch:
      include:
      - master
- name: Deploy PR
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: |-
        cd deployment
        ls -l /bin/bash
        sed -i "s/BRANCH/${CICD_GIT_BRANCH}/g" pr-dev-deployment.yaml
        sed -i "s/BUILD_NUM/build${CICD_EXECUTION_SEQUENCE}/g" pr-dev-deployment.yaml
        sed -i "/^ / s/_/-/" pr-dev-deployment.yaml
        sed -i "33 s|.*|        image: 127.0.0.1:34422/covidsc-web:${CICD_GIT_BRANCH}|" pr-dev-deployment.yaml
  - applyYamlConfig:
      path: ./deployment/pr-dev-deployment.yaml
    when:
      branch: {}
  when:
    branch:
      exclude:
      - master
timeout: 60
branch: {}
notification:
  recipients:
  - recipient: '#systems'
    notifier: c-8nmz6:n-4wkxt
  condition:
  - Success
  - Failed
